name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/**
      - packages/**

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release-please:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    outputs:
      manifest: ${{ toJSON(steps.rp.outputs) }}
    steps:
      - name: Generate App Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Release Please
        id: rp
        uses: GoogleCloudPlatform/release-please-action@v4.1.3
        with:
          token: ${{ steps.generate-token.outputs.token }}
